activation: sigmoid
epochs: 2000
initializer: random_normal
learning_rate: 1.0255105606020227
nb_layers: !!python/tuple
- 3
- units_layer_1: 36.0
  units_layer_2: 32.0
  units_layer_3: 28.0
optimizer: RMSprop
